import { env } from "cloudflare:workers";
import { eq } from "drizzle-orm";
import { getChatGPTUser } from "../../../chatgpt-auth";
import { getDb } from "../../../../db";
import { auditEvents, gameSubmissions, submissionCaptures, users } from "../../../../db/schema";

const MAX_PAGE_BYTES = 512_000;
const MAX_IMAGE_BYTES = 5 * 1024 * 1024;
const USER_AGENT = "MyRPGBot/1.0 (+https://myrpg.io/editorial-standards)";
const imageTypes = new Map([["image/jpeg", "jpg"], ["image/png", "png"], ["image/webp", "webp"], ["image/avif", "avif"]]);
const stamp = () => new Date().toISOString();

function normalizeUrl(value: string) { const url = new URL(value); if (url.protocol !== "https:") throw new Error("HTTPS is required."); url.hash = ""; for (const key of [...url.searchParams.keys()]) if (key.toLowerCase().startsWith("utm_")) url.searchParams.delete(key); return url.toString().replace(/\/$/, ""); }
function host(value: string) { return new URL(value).hostname.toLowerCase().replace(/^www\./, ""); }
function allowedHost(target: string, candidates: string[]) { const targetHost = host(target); return candidates.some((candidate) => targetHost === candidate || targetHost.endsWith(`.${candidate}`)); }
function meta(html: string, names: string[]) { for (const tag of html.match(/<meta\b[^>]*>/gi) || []) { const property = tag.match(/\b(?:property|name)=["']([^"']+)["']/i)?.[1]?.toLowerCase(); const content = tag.match(/\bcontent=["']([^"']+)["']/i)?.[1]; if (property && content && names.includes(property)) return content.trim(); } return ""; }
function title(html: string) { return html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/\s+/g, " ").trim().slice(0, 240) || null; }
function robotsAllows(robots: string, path: string) { const lines = robots.replace(/\r/g, "").split("\n"); let active = false; const rules: string[] = []; for (const raw of lines) { const line = raw.split("#")[0].trim(); if (!line) continue; const [key, ...rest] = line.split(":"); const value = rest.join(":").trim(); if (key.toLowerCase() === "user-agent") { active = value === "*" || value.toLowerCase() === "myrpgbot"; continue; } if (active && key.toLowerCase() === "disallow" && value) rules.push(value); } return !rules.some((rule) => rule === "/" || path.startsWith(rule)); }
async function readLimited(response: Response, limit: number) { const reader = response.body?.getReader(); if (!reader) return new Uint8Array(); const chunks: Uint8Array[] = []; let size = 0; while (true) { const next = await reader.read(); if (next.done) break; size += next.value.byteLength; if (size > limit) throw new Error(`Response exceeded the ${Math.round(limit / 1024)} KB safety limit.`); chunks.push(next.value); } const result = new Uint8Array(size); let offset = 0; for (const chunk of chunks) { result.set(chunk, offset); offset += chunk.byteLength; } return result; }
function validImage(bytes: Uint8Array, type: string) { return type === "image/jpeg" ? bytes[0] === 0xff && bytes[1] === 0xd8 : type === "image/png" ? bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47 : type === "image/webp" ? new TextDecoder().decode(bytes.slice(0, 4)) === "RIFF" && new TextDecoder().decode(bytes.slice(8, 12)) === "WEBP" : type === "image/avif" && new TextDecoder().decode(bytes.slice(4, 8)) === "ftyp"; }

export async function POST(request: Request) {
  const identity = await getChatGPTUser(); if (!identity) return Response.json({ error: "Sign in required." }, { status: 401 });
  const db = getDb(); const owner = (await db.select().from(users).where(eq(users.email, identity.email)).limit(1))[0]; if (owner?.role !== "owner") return Response.json({ error: "Only the Owner can trigger creator-permitted retrieval or capture." }, { status: 403 });
  const body = await request.json() as { submissionId?: string; targetUrl?: string }; const submissionId = String(body.submissionId || ""); const submission = (await db.select().from(gameSubmissions).where(eq(gameSubmissions.id, submissionId)).limit(1))[0];
  if (!submission) return Response.json({ error: "Creator submission not found." }, { status: 404 });
  if (!submission.officialCrawlPermission) return Response.json({ error: "The creator did not permit official-site retrieval for this submission." }, { status: 409 });
  let targetUrl = ""; try { targetUrl = normalizeUrl(String(body.targetUrl || submission.officialUrl)); } catch { return Response.json({ error: "Use a complete HTTPS URL." }, { status: 400 }); }
  const allowed = [host(submission.officialUrl), submission.sourceUrl ? host(submission.sourceUrl) : ""].filter(Boolean); if (!allowedHost(targetUrl, allowed)) return Response.json({ error: "Use the submitted official domain or one of its subdomains only." }, { status: 400 });
  const now = stamp(); const captureId = crypto.randomUUID(); const target = new URL(targetUrl); const robotsUrl = `${target.protocol}//${target.host}/robots.txt`; const permissions = { officialCrawlPermission: submission.officialCrawlPermission, promotionalCapturePermission: submission.promotionalCapturePermission, editorialUsePermission: submission.editorialUsePermission, privateOnly: true, autoPublish: false };
  const write = async (values: { robotsStatus: string; status: string; pageTitle?: string | null; imageUrl?: string | null; r2Key?: string | null; contentType?: string | null; bytes?: number | null; error?: string | null }) => { await db.insert(submissionCaptures).values({ id: captureId, submissionId: submission.id, targetUrl, normalizedUrl: targetUrl, robotsUrl, robotsStatus: values.robotsStatus, pageTitle: values.pageTitle || null, imageUrl: values.imageUrl || null, r2Key: values.r2Key || null, contentType: values.contentType || null, bytes: values.bytes || null, status: values.status, error: values.error || null, permissionsJson: JSON.stringify(permissions), createdAt: now, updatedAt: now }); await db.insert(auditEvents).values({ id: crypto.randomUUID(), actorEmail: identity.email, action: `submission_capture_${values.status}`, entityType: "submission_capture", entityId: captureId, details: JSON.stringify({ submissionId: submission.id, targetUrl, robotsUrl, ...permissions, error: values.error || null }), createdAt: now }); };
  try {
    const robotsResponse = await fetch(robotsUrl, { headers: { "user-agent": USER_AGENT, accept: "text/plain" }, redirect: "manual", signal: AbortSignal.timeout(8_000) });
    let robotsStatus = "missing_allow"; if (robotsResponse.status === 404) robotsStatus = "missing_allow"; else if (!robotsResponse.ok || robotsResponse.type === "opaqueredirect") { await write({ robotsStatus: "unavailable_block", status: "blocked", error: `robots.txt could not be read safely (${robotsResponse.status}).` }); return Response.json({ error: "robots.txt could not be read safely; no page was retrieved." }, { status: 409 }); } else { const robots = new TextDecoder().decode(await readLimited(robotsResponse, 128_000)); if (!robotsAllows(robots, target.pathname || "/")) { await write({ robotsStatus: "disallowed", status: "blocked", error: "robots.txt disallows this path for MyRPGBot." }); return Response.json({ error: "robots.txt disallows this page; nothing was retrieved." }, { status: 409 }); } robotsStatus = "allowed"; }
    const pageResponse = await fetch(targetUrl, { headers: { "user-agent": USER_AGENT, accept: "text/html,application/xhtml+xml" }, redirect: "manual", signal: AbortSignal.timeout(10_000) }); if (!pageResponse.ok || pageResponse.type === "opaqueredirect" || !/html/i.test(pageResponse.headers.get("content-type") || "")) { await write({ robotsStatus, status: "blocked", error: "The official page did not return direct HTML." }); return Response.json({ error: "The official page did not return direct HTML; no capture was created." }, { status: 409 }); }
    const html = new TextDecoder().decode(await readLimited(pageResponse, MAX_PAGE_BYTES)); const pageTitle = title(html); const discovered = meta(html, ["og:image", "twitter:image"]); if (!submission.promotionalCapturePermission || !discovered) { await write({ robotsStatus, status: "evidence_ready", pageTitle }); return Response.json({ ok: true, status: "evidence_ready", pageTitle, captured: false }); }
    let imageUrl = ""; try { imageUrl = normalizeUrl(new URL(discovered, targetUrl).toString()); } catch { await write({ robotsStatus, status: "evidence_ready", pageTitle, error: "The page image metadata was not a valid HTTPS URL." }); return Response.json({ ok: true, status: "evidence_ready", pageTitle, captured: false }); }
    if (!allowedHost(imageUrl, allowed)) { await write({ robotsStatus, status: "evidence_ready", pageTitle, imageUrl, error: "The discovered image is hosted outside the creator-permitted domain." }); return Response.json({ ok: true, status: "evidence_ready", pageTitle, captured: false }); }
    const imageResponse = await fetch(imageUrl, { headers: { "user-agent": USER_AGENT, accept: "image/avif,image/webp,image/png,image/jpeg" }, redirect: "manual", signal: AbortSignal.timeout(10_000) }); const contentType = (imageResponse.headers.get("content-type") || "").split(";")[0].toLowerCase(); if (!imageResponse.ok || imageResponse.type === "opaqueredirect" || !imageTypes.has(contentType)) { await write({ robotsStatus, status: "evidence_ready", pageTitle, imageUrl, error: "No supported same-domain promotional image could be captured." }); return Response.json({ ok: true, status: "evidence_ready", pageTitle, captured: false }); }
    const bytes = await readLimited(imageResponse, MAX_IMAGE_BYTES); if (bytes.length < 32 || !validImage(bytes, contentType)) { await write({ robotsStatus, status: "evidence_ready", pageTitle, imageUrl, error: "The promotional image signature did not match its declared type." }); return Response.json({ ok: true, status: "evidence_ready", pageTitle, captured: false }); }
    const r2Key = `submission-captures/${now.slice(0, 10)}/${captureId}.${imageTypes.get(contentType)}`; await env.MEDIA.put(r2Key, bytes, { httpMetadata: { contentType, cacheControl: "private, no-store" }, customMetadata: { submissionId: submission.id, captureId, visibility: "private_review", permissions: JSON.stringify(permissions) } }); await write({ robotsStatus, status: "private_review", pageTitle, imageUrl, r2Key, contentType, bytes: bytes.byteLength }); return Response.json({ ok: true, status: "private_review", pageTitle, captured: true });
  } catch (error) { const message = error instanceof Error ? error.message : "Unknown retrieval error"; await write({ robotsStatus: "error", status: "blocked", error: message }); return Response.json({ error: "The bounded retrieval was held safely. Review the private audit record for the reason." }, { status: 409 }); }
}
