import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { PublicFooter, PublicHeader } from "../../components/PublicChrome";

export const metadata: Metadata = {
  title: "xVendetta: Browser Crime / Action Public Beta | MyRPG Network Feature",
  description: "A clearly labelled owner-operated MyRPG Network Feature about xVendetta, a browser crime / action game in public beta.",
  alternates: { canonical: "https://myrpg.io/network/xvendetta" },
  openGraph: { type: "website", url: "https://myrpg.io/network/xvendetta", title: "xVendetta: Browser Crime / Action Public Beta", description: "A clearly labelled owner-operated MyRPG Network Feature about xVendetta.", images: [{ url: "/xvendetta/game-dashboard.png", width: 1265, height: 712, alt: "Owner-supplied xVendetta public-beta game interface with its crime/action dashboard and sign-in panel" }] },
  twitter: { card: "summary_large_image", title: "xVendetta: Browser Crime / Action Public Beta", description: "A clearly labelled owner-operated MyRPG Network Feature about xVendetta.", images: ["/xvendetta/game-dashboard.png"] },
};

export default function XVendettaNetworkFeature() {
  return <><PublicHeader /><main id="main-content" className="network-feature-page xvendetta-feature-page">
    <nav aria-label="Breadcrumb" className="network-feature-breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">/</span><Link href="/advertising-disclosure">Network disclosure</Link><span aria-hidden="true">/</span><span>xVendetta</span></nav>
    <header className="xvendetta-feature-hero"><div className="xvendetta-feature-hero-art" aria-hidden="true" /><div className="xvendetta-feature-hero-copy"><p className="network-feature-kicker">MYRPG NETWORK FEATURE · OWNER-OPERATED</p><h1>New Liberty.<br /><em>New rules.</em></h1><p>xVendetta is a browser crime / action game in public beta. Its public interface presents connected systems for crime, street activity, training, gear, work, city life, crews, territory, and player progression.</p><div className="network-feature-actions"><a className="network-feature-primary" href="https://xvendetta.com/" target="_blank" rel="noopener sponsored">Visit xVendetta <span aria-hidden="true">→</span></a><a className="network-feature-secondary" href="https://xvendetta.com/" target="_blank" rel="noopener sponsored">Explore the public beta</a></div></div></header>
    <aside className="network-feature-disclosure" aria-label="Ownership and editorial disclosure"><strong>Ownership disclosure</strong><p>xVendetta is operated by the owner of MyRPG.IO. This is a clearly labelled promotional Network Feature, not an independent editorial review, rating, or recommendation. The interface image below is owner-supplied public-beta game material and was checked on August 8, 2026.</p></aside>
    <article className="network-feature-body"><section className="xvendetta-feature-layout" aria-labelledby="xvendetta-system-title"><div><p className="network-feature-section-label">PUBLIC BETA INTERFACE</p><h2 id="xvendetta-system-title">A city of connected systems.</h2><p>The public xVendetta interface identifies Crime, Street, Gym, Academy, Work, Gear, City, Crew, Territory, Garage, Market, and Businesses as distinct game areas. This feature intentionally describes only those visible official systems; it does not make independent balance, progression, or player-experience claims.</p><p className="network-feature-gameplay-note">Owner-supplied screenshot — public-beta interface, for product illustration only. No player records, rankings, or third-party media are used.</p></div><figure className="xvendetta-feature-screenshot"><Image src="/xvendetta/game-dashboard.png" width={1265} height={712} sizes="(max-width: 900px) calc(100vw - 76px), 620px" alt="Owner-supplied xVendetta public-beta dashboard with crime/action navigation, public-beta notice, and a sign-in panel." priority /><figcaption>Owner-supplied xVendetta gameplay interface — public beta; not an independent review.</figcaption></figure></section><footer className="network-feature-source"><p><strong>Official source:</strong> <a href="https://xvendetta.com/" target="_blank" rel="noopener sponsored">xVendetta.com</a></p><p><strong>Fact-checked:</strong> August 8, 2026</p><p><strong>Editorial status:</strong> Owner-operated network feature; promotional placement; no score or independent-review claim.</p></footer></article>
  </main><PublicFooter /></>;
}
