"use client";
import { useState } from "react";

export default function TimelineManager({ role, games, events, articles, calendarItems, corrections }: any) {
  const [message,setMessage]=useState(""); const send=async(body:any)=>{const response=await fetch("/api/admin/actions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();setMessage(result.error||"Saved. Refreshing…");if(result.ok)setTimeout(()=>location.reload(),500)};
  return <main className="console"><p>MYRPG / GAME HISTORY</p><h1>Timeline management</h1><p>Private source-first milestones. Nothing publishes without an explicit Owner decision.</p>
    <section><h2>Create private timeline event</h2><form className="source-form" onSubmit={(event)=>{event.preventDefault();send({kind:"timeline",action:"create",...Object.fromEntries(new FormData(event.currentTarget))})}}><select name="gameId" required><option value="">Published game</option>{games.map((game:any)=><option key={game.id} value={game.id}>{game.name}</option>)}</select><input name="title" placeholder="Factual event title" required/><textarea name="explanation" placeholder="Short factual explanation" required/><select name="eventType" required>{["launch","early_access_launch","major_update","platform_release","confirmed_delay","status_change","business_model_change","sunset","material_correction"].map(value=><option key={value}>{value}</option>)}</select><input name="eventDate" type="date" required/><select name="dateConfidence"><option>confirmed</option><option>estimated</option><option>unconfirmed</option></select><input name="sourceUrl" type="url" placeholder="Approved official source URL" required/><input name="citation" placeholder="Visible source label" required/><input name="factCheckedAt" type="date" required/><select name="confidence"><option>high</option><option>medium</option><option>low</option></select><select name="articleId"><option value="">Optional published article</option>{articles.map((item:any)=><option key={item.id} value={item.id}>{item.title}</option>)}</select><select name="calendarItemId"><option value="">Optional calendar item</option>{calendarItems.map((item:any)=><option key={item.id} value={item.id}>{item.title}</option>)}</select><button>Create private event</button></form></section>
    <section><h2>Timeline review queue</h2><div className="console-grid">{events.map((item:any)=>{const blocker=item.reviewStatus!=="approved"?"Owner review decision required.":item.dateConfidence==="unconfirmed"?"Date confidence remains unresolved.":null;const recommendation=item.reviewStatus==="draft"&&item.dateConfidence==="confirmed"?"Approve after verifying the linked official source.":item.reviewStatus==="approved"&&!blocker?"Publish when the Owner is satisfied.":item.reviewStatus==="rejected"?"Keep rejected or archive.":item.reviewStatus==="archived"?"Keep archived unless new evidence supports restoration.":"Hold until the blocker is resolved.";return <article className="console-card" key={item.id}><small>{item.reviewStatus} · {item.dateConfidence}</small><h3>{item.title}</h3><p>{item.explanation}</p><p><a href={item.sourceUrl} target="_blank" rel="noopener noreferrer">Official source</a></p><p>{blocker?`Blocker: ${blocker}`:"Ready for Owner publication."}</p><p><strong>Recommendation:</strong> {recommendation}</p><div className="row"><button onClick={()=>send({kind:"timeline",action:"approve",id:item.id})} disabled={role!=="owner"}>Approve</button><button onClick={()=>send({kind:"timeline",action:"publish",id:item.id})} disabled={role!=="owner"||item.reviewStatus!=="approved"}>Publish</button><button onClick={()=>send({kind:"timeline",action:"reject",id:item.id})}>Reject</button><button onClick={()=>send({kind:"timeline",action:"archive",id:item.id})}>Archive</button></div></article>})}</div></section>
    <section><h2>Create public correction record</h2><p>Owner-only. Create privately, then publish after verifying the affected public page.</p><form className="source-form" onSubmit={(event)=>{event.preventDefault();send({kind:"correction",action:"create",...Object.fromEntries(new FormData(event.currentTarget))})}}><select name="correctionType"><option>correction</option><option>update</option><option>clarification</option></select><select name="targetType"><option>game</option><option>article</option></select><select name="targetId" required><option value="">Affected public record</option>{games.map((item:any)=><option key={`g-${item.id}`} value={item.id}>{item.name}</option>)}{articles.map((item:any)=><option key={`a-${item.id}`} value={item.id}>{item.title}</option>)}</select><textarea name="summary" placeholder="What changed" required/><textarea name="reason" placeholder="Why it changed" required/><input name="sourceUrl" type="url" placeholder="Current approved source" required/><button disabled={role!=="owner"}>Create private correction</button></form><div className="console-grid">{corrections.map((item:any)=><article className="console-card" key={item.id}><small>{item.correctionType} · {item.reviewStatus}</small><h3>{item.summary}</h3><p>{item.reason}</p><button onClick={()=>send({kind:"correction",action:"publish",id:item.id})} disabled={role!=="owner"||item.published}>Publish correction</button></article>)}</div></section>{message&&<p className="console-message">{message}</p>}<p><a href="/admin">Return to Director Console</a></p></main>;
}
