"use client";

import { useMemo, useState } from "react";

type Game = { name: string; status: "Live" | "Early access" | "Announced"; platform: string; model: string; combat: string; setting: string; focus: string; date: string; confirmed?: boolean; tag: string };

const games: Game[] = [
  { name: "Final Fantasy XIV", status: "Live", platform: "PC · PS5 · Xbox", model: "Subscription", combat: "Tab-target", setting: "High fantasy", focus: "PvE", date: "Live now", tag: "Community" },
  { name: "Dune: Awakening", status: "Live", platform: "PC", model: "Buy to play", combat: "Action", setting: "Sci-fi", focus: "PvPvE", date: "Live now", tag: "Survival" },
  { name: "Chrono Odyssey", status: "Announced", platform: "PC · PS5 · Xbox", model: "TBA", combat: "Action", setting: "Dark fantasy", focus: "PvE / PvP", date: "2026", tag: "Watch" },
  { name: "Pax Dei", status: "Early access", platform: "PC", model: "Subscription", combat: "Sandbox", setting: "Medieval", focus: "PvP", date: "Early access", tag: "Sandbox" },
  { name: "Guild Wars 2", status: "Live", platform: "PC", model: "Buy to play", combat: "Action", setting: "Fantasy", focus: "PvE", date: "Live now", tag: "Expansions" },
  { name: "Corepunk", status: "Early access", platform: "PC", model: "Buy to play", combat: "Isometric", setting: "Fantasy", focus: "PvP", date: "Early access", tag: "Open world" },
];

const stories = [
  { title: "The MMO release calendar is getting crowded again", game: "Discovery", type: "Market watch", time: "12 min ago", source: "Official developer updates", copy: "A fact-checked look at the confirmed launches, test windows, and games still using broad release targets." },
  { title: "Guild Wars 2 outlines its next seasonal update", game: "Guild Wars 2", type: "Patch notes", time: "48 min ago", source: "ArenaNet", copy: "The update focuses on instanced content, rewards, and quality-of-life changes for returning players." },
  { title: "Pax Dei shares its next alpha priorities", game: "Pax Dei", type: "Development", time: "2 hr ago", source: "Mainframe Industries", copy: "The studio detailed its approach to social systems, territory control, and performance improvements." },
];

export default function Home() {
  const [view, setView] = useState<"home" | "news" | "directory" | "calendar" | "compare" | "admin">("home");
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("All");
  const [selected, setSelected] = useState<string[]>(["Final Fantasy XIV", "Dune: Awakening"]);
  const [queue, setQueue] = useState([
    { title: "Chrono Odyssey: the current release picture", agent: "Validator", confidence: "94%", state: "Needs review" },
    { title: "Pax Dei territory system explainer", agent: "Editor", confidence: "88%", state: "Needs review" },
    { title: "New MMO discovery candidate", agent: "Research", confidence: "72%", state: "Flagged" },
  ]);
  const filtered = useMemo(() => games.filter(g => g.name.toLowerCase().includes(query.toLowerCase()) && (status === "All" || g.status === status)), [query, status]);
  const nav = (label: string, key: typeof view) => <button className={view === key ? "nav active" : "nav"} onClick={() => setView(key)}>{label}</button>;
  const toggleGame = (name: string) => setSelected(prev => prev.includes(name) ? prev.filter(x => x !== name) : prev.length < 3 ? [...prev, name] : prev);

  return <main>
    <header className="topbar">
      <button className="brand" onClick={() => setView("home")} aria-label="MyRPG home"><span>MY</span>RPG<span className="dot">.IO</span></button>
      <nav aria-label="Primary navigation">{nav("News", "news")}{nav("Games", "directory")}{nav("Calendar", "calendar")}{nav("Compare", "compare")}</nav>
      <div className="top-actions"><span className="signal">● VERIFIED SOURCES</span><button className="admin-button" onClick={() => setView("admin")}>Director console ↗</button></div>
    </header>

    {view === "home" && <>
      <section className="hero"><div className="eyebrow">MMO INTELLIGENCE, HUMAN-APPROVED</div><h1>Know what’s next.<br/><em>Play what fits.</em></h1><p>News, games, and release signals for players who want less noise and more useful MMO context.</p><div className="hero-actions"><button className="primary" onClick={() => setView("directory")}>Explore the directory</button><button className="quiet" onClick={() => setView("calendar")}>See release calendar →</button></div><div className="hero-meta"><span><b>42</b> tracked worlds</span><span><b>100%</b> source-linked drafts</span><span><b>0</b> auto-published stories</span></div></section>
      <section className="feature-grid"><article className="featured-card"><div className="card-kicker">FEATURED BRIEF <span>DEMO CONTENT</span></div><h2>What to watch in the next generation of online worlds</h2><p>From persistent sandboxes to familiar worlds finding a second wind, this is the signal map for the months ahead.</p><button className="text-button" onClick={() => setView("news")}>Read the brief →</button><div className="feature-orbit"><i></i><i></i><i></i><b>LIVE<br/>SIGNAL</b></div></article><aside className="watchlist"><div className="section-head"><span>GAMES TO WATCH</span><button onClick={() => setView("directory")}>Full directory →</button></div>{games.slice(2, 5).map((g, i) => <div className="watch" key={g.name}><span className="rank">0{i + 1}</span><div><b>{g.name}</b><small>{g.status} · {g.setting}</small></div><span className="watch-tag">{g.tag}</span></div>)}</aside></section>
      <section className="section-block"><div className="section-head"><div><span className="eyebrow">LATEST SIGNAL</span><h2>Useful updates, without the sludge.</h2></div><button onClick={() => setView("news")}>All news →</button></div><div className="news-grid">{stories.map(s => <article className="story" key={s.title}><div><span className="story-type">{s.type}</span><span className="time">{s.time}</span></div><h3>{s.title}</h3><p>{s.copy}</p><footer><b>{s.game}</b><small>Source: {s.source}</small></footer></article>)}</div></section>
      <section className="calendar-strip"><div><span className="eyebrow">RELEASE RADAR</span><h2>Dates worth pinning.</h2></div><div className="date-item"><b>Q3 2026</b><span>Chrono Odyssey</span><small>Estimated</small></div><div className="date-item confirmed"><b>AUG 18</b><span>Guild Wars 2 update</span><small>Confirmed</small></div><button onClick={() => setView("calendar")}>Open calendar →</button></section>
    </>}

    {view === "news" && <section className="page"><div className="eyebrow">NEWS DESK</div><h1>Every update has a trail.</h1><p className="lede">MyRPG drafts are compiled from approved sources, then reviewed before publication. The cards below are seeded demonstration content.</p><div className="news-list">{[...stories, ...stories].map((s, i) => <article className="news-row" key={i}><span className="news-index">0{i + 1}</span><div><div className="row-meta"><span>{s.type}</span><span>{s.time}</span><span>AI-assisted · Human approved</span></div><h2>{s.title}</h2><p>{s.copy}</p><a href="#sources">Source: {s.source} ↗</a></div><button className="save">Save</button></article>)}</div></section>}

    {view === "directory" && <section className="page"><div className="eyebrow">GAME DIRECTORY</div><h1>Find a world worth your time.</h1><div className="filterbar"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search games" aria-label="Search games"/><div className="pills">{["All", "Live", "Early access", "Announced"].map(x => <button key={x} onClick={() => setStatus(x)} className={status === x ? "selected" : ""}>{x}</button>)}</div></div><p className="filter-note">Demo directory · {filtered.length} matching games · Compare up to three.</p><div className="game-grid">{filtered.map(g => <article className="game" key={g.name}><div className="game-art"><span>{g.tag}</span><b>{g.name.slice(0, 2).toUpperCase()}</b></div><div className="game-body"><div><span className={`status ${g.status.replace(" ", "-").toLowerCase()}`}>{g.status}</span><button className={selected.includes(g.name) ? "compare-toggle on" : "compare-toggle"} onClick={() => toggleGame(g.name)}>{selected.includes(g.name) ? "Selected" : "Compare"}</button></div><h2>{g.name}</h2><p>{g.setting} · {g.combat} · {g.focus}</p><small>{g.platform} · {g.model}</small></div></article>)}</div><button className="primary floating" onClick={() => setView("compare")}>Compare {selected.length} games →</button></section>}

    {view === "calendar" && <section className="page"><div className="eyebrow">RELEASE CALENDAR</div><h1>Put the real dates on your radar.</h1><p className="lede">Confirmed dates are marked in cyan. Estimates are deliberately separated so guesses never look like announcements.</p><div className="calendar-table">{[{date:"AUG 18",game:"Guild Wars 2 · Seasonal update",state:"Confirmed",kind:"confirmed"},{date:"SEP 2026",game:"Corepunk · Content milestone",state:"Estimated",kind:"estimate"},{date:"2026",game:"Chrono Odyssey · Release window",state:"Estimated",kind:"estimate"},{date:"TBA",game:"Pax Dei · Major update",state:"Awaiting official date",kind:"tba"}].map(r=><div className="calendar-row" key={r.game}><b>{r.date}</b><span>{r.game}</span><i className={r.kind}>{r.state}</i><button>Track +</button></div>)}</div></section>}

    {view === "compare" && <section className="page"><div className="eyebrow">COMPARE WORLDS</div><h1>Pick the better fit, not the louder launch.</h1><p className="lede">Select up to three games in the directory. This comparison uses structured facts, which makes it easy to see what actually differs.</p><div className="compare-table"><div className="compare-head"><span>Core detail</span>{selected.map(n => <b key={n}>{n}</b>)}</div>{[["Status", "status"],["Platforms", "platform"],["Business model", "model"],["Combat", "combat"],["Setting", "setting"],["Focus", "focus"],["Release", "date"]].map(([label,key])=><div className="compare-row" key={label}><span>{label}</span>{selected.map(n => <b key={n}>{games.find(g=>g.name===n)?.[key as keyof Game] as string}</b>)}</div>)}</div><button className="quiet" onClick={() => setView("directory")}>← Change your selections</button></section>}

    {view === "admin" && <section className="console"><aside className="console-side"><span className="console-mark">MYRPG / DIRECTOR</span><b>Operations</b>{["Review queue", "Agent runs", "Content library", "Sources", "Budget controls", "Sponsors"].map((x,i)=><button className={i===0?"side-active":""} key={x}>{x}<small>{i===0?3:""}</small></button>)}<div className="side-foot">Signed in as <b>Owner</b><span>Demo environment</span></div></aside><div className="console-main"><div className="console-top"><div><span className="eyebrow">OWNER-ONLY WORKSPACE</span><h1>Review before it reaches players.</h1></div><button className="primary">Run discovery scan</button></div><div className="metrics"><div><span>Queued drafts</span><b>03</b><small>All require approval</small></div><div><span>Source integrity</span><b>96.4%</b><small>Last check: 8 min ago</small></div><div><span>Daily model budget</span><b>$1.84 <i>/ $8.00</i></b><small>23% used</small></div><div><span>Publish automation</span><b>OFF</b><small>Human approval required</small></div></div><section className="queue"><div className="section-head"><div><span className="eyebrow">REVIEW QUEUE</span><h2>Drafts awaiting your call</h2></div><button>View archive →</button></div>{queue.map((q,i)=><article className="queue-row" key={q.title}><div className="agent-avatar">{q.agent[0]}</div><div><span className="row-meta"><b>{q.agent} agent</b> · {q.confidence} confidence · 2 approved sources</span><h3>{q.title}</h3><small>Created today · Fact-check due before publishing</small></div><span className={q.state === "Flagged" ? "flagged" : "needs"}>{q.state}</span><div className="queue-actions"><button onClick={()=>setQueue(prev=>prev.filter((_,x)=>x!==i))}>Reject</button><button>Preview</button><button className="approve" onClick={()=>setQueue(prev=>prev.filter((_,x)=>x!==i))}>Approve</button></div></article>)}</section><section className="audit"><div><span className="eyebrow">AGENT AUDIT TRAIL</span><h2>What the system did — and why.</h2></div><div className="audit-list"><p><b>Validator</b> blocked a duplicate release claim <span>· source conflict detected</span></p><p><b>Research</b> added a developer post to the approved-source registry <span>· official domain</span></p><p><b>Editor</b> prepared 2 structured drafts <span>· not published</span></p></div></section></div></section>}

    {view !== "admin" && <aside style={{maxWidth:1250,margin:"0 auto 52px",padding:"0 25px"}} aria-label="Featured game from the MyRPG network"><div style={{border:"1px solid #705421",background:"linear-gradient(110deg,#12100d,#1b1610)",padding:"26px 30px",display:"flex",gap:20,justifyContent:"space-between",alignItems:"center",borderLeft:"3px solid #c9a666"}}><div><p style={{color:"#c9a666",fontSize:10,letterSpacing:1.5,margin:0}}>FEATURED GAME FROM THE MYRPG NETWORK</p><h2 style={{margin:"9px 0",fontSize:27}}>MyMafia.io — Build an empire. Keep an alibi.</h2><p style={{margin:0,color:"#bdb4a7",maxWidth:650}}>A browser strategy MMORPG where crimes become careers, allies become families, and every city keeps a secret.</p></div><a href="https://mymafia.io?utm_source=myrpg.io&utm_medium=network_promo&utm_campaign=mymafia_beta" target="_blank" rel="noopener sponsored" style={{whiteSpace:"nowrap",color:"#16110a",background:"#c9a666",padding:"12px 16px",textDecoration:"none",fontWeight:800,fontSize:12}}>Explore MyMafia →</a></div></aside>}
    <footer><div className="brand"><span>MY</span>RPG<span className="dot">.IO</span></div><p>MMO intelligence with human accountability. Demo content is clearly marked and not live editorial reporting.</p><div><a href="#policy">Editorial standards</a><a href="#policy">AI transparency</a><a href="#policy">Advertising disclosure</a><a href="#policy">Privacy</a></div></footer>
  </main>;
}
