import { and, desc, eq } from "drizzle-orm";
import { getDb } from "../db";
import { articles, calendarItems, games, mediaAssets, siteSettings } from "../db/schema";
import { editorialGraphic, publicEditorialAssetUrl } from "./components/editorial-media";
import { NetworkFeature, PublicFooter, PublicHeader } from "./components/PublicChrome";

export const dynamic = "force-dynamic";
export const metadata = { alternates: { canonical: "/" } };

export default async function Home() {
  let news: any[] = [], featured: any[] = [], releases: any[] = [], showNetwork = true;
  const articleVisuals = new Map<string, any>(), gameVisuals = new Map<string, any>();
  try {
    const db = getDb(); const [articleRows, gameRows, releaseRows, settings, approved] = await Promise.all([
      db.select().from(articles).where(eq(articles.status, "published")).orderBy(desc(articles.publishedAt)).limit(3), db.select().from(games).where(eq(games.published, true)).limit(6),
      db.select({ item: calendarItems, game: games }).from(calendarItems).innerJoin(games, eq(calendarItems.gameId, games.id)).where(and(eq(calendarItems.published, true), eq(games.published, true), eq(calendarItems.dateConfidence, "confirmed"))).limit(4),
      db.select().from(siteSettings).limit(1), db.select().from(mediaAssets).where(and(eq(mediaAssets.status, "approved"), eq(mediaAssets.placement, "lead"))),
    ]);
    news = articleRows; featured = gameRows; releases = releaseRows; showNetwork = settings[0]?.networkPromotionsEnabled ?? true;
    for (const asset of approved) { if (asset.articleId && !articleVisuals.has(asset.articleId)) articleVisuals.set(asset.articleId, asset); if (asset.gameId && !gameVisuals.has(asset.gameId)) gameVisuals.set(asset.gameId, asset); }
  } catch { /* Public empty states intentionally conceal storage failures. */ }
  return <><PublicHeader /><main style={shell}><section style={hero}><p style={eyebrow}>MMO INTELLIGENCE, HUMAN-APPROVED</p><h1 style={title}>Know what’s next.<br /><em style={{ color: "#76f5e3" }}>Play what fits.</em></h1><p style={lede}>Source-linked MMO news, factual game profiles, and useful discovery tools—built to help players decide without the noise.</p><p><a href="/find-my-mmo" style={primary}>Find My MMO →</a> <a href="/games" style={secondary}>Explore the directory</a></p></section>
    <section style={grid}><section style={panel}><p style={eyebrow}>LATEST NEWS</p><h2 style={h2}>Source-linked editorial updates</h2>{news.length ? news.map((article) => <article key={article.id} style={item}><CompactVisual title={article.title} image={articleVisuals.get(article.id)} graphic={article.editorialGraphic} /><a href={`/articles/${article.slug}`} style={link}><h3>{article.title}</h3></a><p style={muted}>{article.summary}</p><small>Recently fact-checked: {article.factCheckedAt?.slice(0, 10)} · AI-assisted, human-reviewed</small></article>) : <Empty title="News is reviewed before it goes live" body="No published editorial coverage is available yet." />}</section><aside style={panel}><p style={eyebrow}>RELEASE RADAR</p><h2 style={h2}>Confirmed dates</h2>{releases.length ? releases.map(({ item, game }) => <article key={item.id} style={item}><strong>{item.dateLabel}</strong><p><a href={`/games/${game.slug}`} style={link}>{item.title}</a></p><small>Confirmed official date · Fact-checked {item.factCheckedAt.slice(0, 10)}</small></article>) : <Empty title="No confirmed dates to pin" body="Unconfirmed and estimated dates stay out of the public release radar." />}</aside></section>
    <section style={section}><p style={eyebrow}>PUBLISHED GAME PROFILES</p><h2 style={h2}>Games to explore</h2><div style={cards}>{featured.length ? featured.map((game) => <article key={game.id} style={card}><CompactVisual title={game.name} image={gameVisuals.get(game.id)} graphic={game.editorialGraphic} /><small style={{ color: "#76f5e3", fontWeight: 800 }}>{game.status.toUpperCase()}</small><h3>{game.name}</h3><p style={muted}>{game.platforms} · {game.businessModel}</p><p><a href={`/games/${game.slug}`} style={link}>View profile →</a></p></article>) : <Empty title="The directory is growing carefully" body="Only owner-published, fact-checked profiles appear here." />}</div></section>
    <section style={section}><p style={eyebrow}>HOW MYRPG WORKS</p><h2 style={h2}>Useful coverage with a visible trail.</h2><div style={cards}><article style={card}><h3>Official sources first</h3><p style={muted}>Developer, publisher, store, press-release, and approved RSS sources only.</p></article><article style={card}><h3>AI-assisted, human-reviewed</h3><p style={muted}>A human Owner decides what is published.</p></article><article style={card}><h3>No autonomous publishing</h3><p style={muted}>Every public record requires manual approval.</p></article></div></section><section style={quick}><a href="/games">Browse games</a><a href="/mmo-radar">MMO Radar</a><a href="/official-updates">Official updates</a><a href="/calendar">Release calendar</a><a href="/compare">Compare games</a><a href="/find-my-mmo">Find My MMO</a></section>{showNetwork && <NetworkFeature />}</main><PublicFooter /></>;
}

function CompactVisual({ title, image, graphic }: { title: string; image?: any; graphic?: string | null }) { const src = publicEditorialAssetUrl(image); const fallback = editorialGraphic(graphic); return <figure style={{ margin: "0 0 14px", position: "relative", aspectRatio: "16 / 9", overflow: "hidden", background: "#101521" }}><img src={src || fallback.src} alt={src ? image.altText : fallback.alt} width={src ? image.width || 1200 : 1600} height={src ? image.height || 675 : 900} loading="lazy" style={{ width: "100%", height: "100%", objectFit: "cover", display: "block" }} /><figcaption style={{ position: "absolute", left: 0, right: 0, bottom: 0, padding: "7px 9px", background: "rgba(5,8,14,.84)", color: "#d6dee8", fontSize: 11 }}>{src ? image.credit || image.caption || "Approved editorial media" : "MyRPG editorial graphic — not gameplay."}</figcaption></figure>; }
function Empty({ title, body }: { title: string; body: string }) { return <article style={{ borderLeft: "3px solid #c9a666", padding: "16px 18px", background: "#101521" }}><h3>{title}</h3><p style={muted}>{body}</p></article>; }
const shell = { minHeight: "100vh", background: "#090b12", color: "#edf3f5", padding: "0 24px 72px" }; const hero = { maxWidth: 1180, margin: "0 auto", padding: "88px 0 54px" }; const eyebrow = { color: "#76f5e3", fontSize: 11, letterSpacing: 1.7, fontWeight: 800 }; const title = { fontSize: "clamp(3rem,8vw,6.6rem)", lineHeight: ".92", letterSpacing: "-.065em", margin: "0 0 22px" }; const lede = { maxWidth: 670, color: "#b8c0cf", fontSize: 18, lineHeight: 1.65 }; const primary = { display: "inline-block", background: "#76f5e3", color: "#06100f", padding: "13px 16px", textDecoration: "none", fontWeight: 900 }; const secondary = { display: "inline-block", border: "1px solid #39445a", color: "#edf3f5", padding: "13px 16px", textDecoration: "none", fontWeight: 800, marginLeft: 10 }; const grid = { maxWidth: 1180, margin: "0 auto", display: "grid", gridTemplateColumns: "minmax(0,1.4fr) minmax(0,.85fr)", gap: 18 }; const panel = { border: "1px solid #273044", background: "#101521", padding: 26 }; const section = { maxWidth: 1180, margin: "46px auto" }; const h2 = { fontSize: 30, letterSpacing: "-.04em" }; const item = { borderTop: "1px solid #273044", padding: "18px 0" }; const muted = { color: "#aeb6c7", lineHeight: 1.6, fontSize: 14 }; const link = { color: "#76f5e3", textDecoration: "none", fontWeight: 800 }; const cards = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 14 }; const card = { border: "1px solid #273044", background: "#101521", padding: 20 }; const quick = { maxWidth: 1180, margin: "0 auto 38px", display: "flex", gap: 12, flexWrap: "wrap" as const };
