import { and, desc, eq } from "drizzle-orm";
import { getDb } from "../db";
import { articles, calendarItems, games, mediaAssets, siteSettings } from "../db/schema";
import { NetworkFeature, PublicFooter, PublicHeader } from "./components/PublicChrome";

export const dynamic = "force-dynamic";

export default async function Home() {
  let news: any[] = []; let featured: any[] = []; let releases: any[] = []; let showNetwork = true; let articleVisuals = new Map<string, any>(); let gameVisuals = new Map<string, any>(); let editorialStatus = { articles: 0, games: 0, calendar: 0, latestFactCheck: null as string | null };
  try { const db = getDb(); const [articleRows, gameRows, releaseRows, settings, approvedVisuals] = await Promise.all([
    db.select().from(articles).where(eq(articles.status, "published")).orderBy(desc(articles.publishedAt)).limit(3),
    db.select().from(games).where(eq(games.published, true)).limit(6),
    db.select({ item: calendarItems, game: games }).from(calendarItems).innerJoin(games, eq(calendarItems.gameId, games.id)).where(and(eq(calendarItems.published, true), eq(games.published, true), eq(calendarItems.dateConfidence, "confirmed"))).limit(4),
    db.select().from(siteSettings).limit(1),
    db.select().from(mediaAssets).where(and(eq(mediaAssets.status, "approved"), eq(mediaAssets.placement, "lead"))),
  ]); news = articleRows; featured = gameRows; releases = releaseRows; showNetwork = settings[0]?.networkPromotionsEnabled ?? true; articleVisuals = new Map(approvedVisuals.filter((asset) => asset.articleId).map((asset) => [asset.articleId!, asset])); gameVisuals = new Map(approvedVisuals.filter((asset) => asset.gameId).map((asset) => [asset.gameId!, asset])); const dates = [...articleRows.map((article) => article.factCheckedAt), ...gameRows.map((game) => game.factCheckedAt), ...releaseRows.map(({ item }) => item.factCheckedAt)].filter(Boolean).sort(); editorialStatus = { articles: articleRows.length, games: gameRows.length, calendar: releaseRows.length, latestFactCheck: dates.at(-1) || null }; } catch { /* Public empty states intentionally hide unavailable data. */ }
  return <><PublicHeader /><main style={shell}>
    <section style={hero}><p style={eyebrow}>MMO INTELLIGENCE, HUMAN-APPROVED</p><h1 style={title}>Know what’s next.<br /><em style={{ color: "#76f5e3" }}>Play what fits.</em></h1><p style={lede}>Source-linked MMO news, factual game profiles, and useful discovery tools—built to help players decide without the noise.</p><div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}><a href="/find-my-mmo" style={primary}>Find My MMO →</a><a href="/games" style={secondary}>Explore the directory</a></div><p style={status}>VERIFIED SOURCES · HUMAN REVIEW REQUIRED · NO AUTONOMOUS PUBLISHING</p></section>
    <section style={grid}><section style={panel}><p style={eyebrow}>LATEST NEWS</p><h2 style={h2}>Source-linked editorial updates</h2>{news.length ? news.map((article) => <article key={article.id} style={item}><CompactVisual title={article.title} image={articleVisuals.get(article.id)} /><a href={`/articles/${article.slug}`} style={link}><h3 style={{ margin: "12px 0 7px" }}>{article.title}</h3></a><p style={muted}>{article.summary}</p><small>Recently fact-checked: {article.factCheckedAt?.slice(0, 10)} · AI-assisted, human-reviewed</small></article>) : <Empty title="News is reviewed before it goes live" body="No published editorial coverage is available yet. MyRPG never fills this space with simulated or unreviewed stories." />}</section>
      <aside style={panel}><p style={eyebrow}>RELEASE RADAR</p><h2 style={h2}>Confirmed dates</h2>{releases.length ? releases.map(({ item, game }) => <article key={item.id} style={item}><strong>{item.dateLabel}</strong><p style={{ margin: "6px 0" }}><a href={`/games/${game.slug}`} style={link}>{item.title}</a></p><small>Confirmed official date · Fact-checked {item.factCheckedAt.slice(0, 10)}</small></article>) : <Empty title="No confirmed dates to pin" body="Unconfirmed and estimated dates stay out of the public release radar." />}</aside>
    </section>
    <section style={{ marginTop: 46 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 16, flexWrap: "wrap", alignItems: "end" }}><div><p style={eyebrow}>PUBLISHED GAME PROFILES</p><h2 style={h2}>Games to explore</h2></div><a href="/games" style={link}>Open game directory →</a></div><div style={cards}>{featured.length ? featured.map((game) => <article key={game.id} style={card}><CompactVisual title={game.name} image={gameVisuals.get(game.id)} /><small style={{ color: "#76f5e3", fontWeight: 800 }}>{game.status.toUpperCase()}</small><h3>{game.name}</h3><p style={muted}>{game.platforms} · {game.businessModel}</p><p style={muted}>{game.setting} · {game.combat} · {game.focus}</p><small>Recently fact-checked: {game.factCheckedAt?.slice(0, 10)}</small><p><a href={`/games/${game.slug}`} style={link}>View profile →</a></p></article>) : <Empty title="The directory is growing carefully" body="Only owner-published, fact-checked game profiles are displayed here." />}</div></section>
    <section style={how}><p style={eyebrow}>HOW MYRPG WORKS</p><h2 style={h2}>Useful coverage with a visible trail.</h2><div style={cards}><article><h3>1. Official sources first</h3><p style={muted}>Developer, publisher, store, press-release, and approved RSS sources only.</p></article><article><h3>2. AI-assisted, human-reviewed</h3><p style={muted}>AI can prepare structured drafts; a human Owner decides what is published.</p></article><article><h3>3. No autonomous publishing</h3><p style={muted}>Every public article, game, date, and media item requires manual approval.</p></article></div><p><a href="/editorial-standards" style={link}>Read editorial standards →</a></p></section>
    <section style={editorial}><p style={eyebrow}>EDITORIAL STATUS</p><h2 style={h2}>Published records, with accountability.</h2><p style={muted}>{editorialStatus.articles} source-linked article{editorialStatus.articles === 1 ? "" : "s"} · {editorialStatus.games} human-reviewed game profile{editorialStatus.games === 1 ? "" : "s"} · {editorialStatus.calendar} confirmed release item{editorialStatus.calendar === 1 ? "" : "s"}.</p>{editorialStatus.latestFactCheck && <p style={{ ...muted, fontSize: 12 }}>Latest stored fact-check date: {editorialStatus.latestFactCheck.slice(0, 10)}.</p>}<p style={{ marginBottom: 0 }}><a href="/editorial-standards" style={link}>Editorial standards</a> <span style={{ color: "#6d7485" }}>·</span> <a href="/ai-transparency" style={link}>AI transparency</a></p></section>
    <section style={quick}><a href="/games">Browse games</a><a href="/calendar">Release calendar</a><a href="/compare">Compare games</a><a href="/find-my-mmo">Find My MMO</a></section>
    {showNetwork && <NetworkFeature />}
  </main><PublicFooter /></>;
}

function Empty({ title, body }: { title: string; body: string }) { return <article style={{ borderLeft: "3px solid #c9a666", padding: "16px 18px", background: "#101521" }}><h3 style={{ marginTop: 0 }}>{title}</h3><p style={muted}>{body}</p></article>; }
function CompactVisual({ title, image }: { title: string; image?: any }) { return image?.assetUrl || image?.sourceUrl ? <figure style={{ margin: 0, position: "relative", aspectRatio: "16 / 9", overflow: "hidden", background: "#101521" }}><img src={image.assetUrl || image.sourceUrl} alt={image.altText || title} width={image.width || 1200} height={image.height || 675} loading="lazy" style={{ width: "100%", height: "100%", objectFit: "cover", display: "block" }} /><figcaption style={{ position: "absolute", left: 0, right: 0, bottom: 0, padding: "7px 9px", background: "rgba(5,8,14,.82)", color: "#d6dee8", fontSize: 11 }}>{image.credit || image.caption || "Approved editorial media"}</figcaption></figure> : <div aria-label="MyRPG editorial graphic — not gameplay" style={{ minHeight: 112, padding: 14, display: "flex", alignItems: "end", background: "linear-gradient(135deg,#11182b,#16263c)", border: "1px solid #31547a", color: "#b7c9d6", fontSize: 11, fontWeight: 800, letterSpacing: .7 }}>MYRPG EDITORIAL GRAPHIC — NOT GAMEPLAY</div>; }
const shell = { minHeight: "100vh", background: "#090b12", color: "#edf3f5", padding: "0 24px 72px" }; const hero = { maxWidth: 1180, margin: "0 auto", padding: "88px 0 54px" }; const eyebrow = { color: "#76f5e3", fontSize: 11, letterSpacing: 1.7, fontWeight: 800, margin: "0 0 10px" }; const title = { fontSize: "clamp(3rem,8vw,6.6rem)", lineHeight: ".92", letterSpacing: "-.065em", margin: "0 0 22px" }; const lede = { maxWidth: 670, color: "#b8c0cf", fontSize: 18, lineHeight: 1.65, marginBottom: 26 }; const primary = { display: "inline-block", background: "#76f5e3", color: "#06100f", padding: "13px 16px", textDecoration: "none", fontWeight: 900 }; const secondary = { display: "inline-block", border: "1px solid #39445a", color: "#edf3f5", padding: "13px 16px", textDecoration: "none", fontWeight: 800 }; const status = { color: "#8f9aad", fontSize: 11, letterSpacing: 1.1, marginTop: 34 }; const grid = { maxWidth: 1180, margin: "0 auto", display: "grid", gridTemplateColumns: "minmax(0,1.4fr) minmax(0,.85fr)", gap: 18 }; const panel = { border: "1px solid #273044", background: "#101521", padding: 26 }; const h2 = { fontSize: 30, letterSpacing: "-.04em", margin: "0 0 18px" }; const item = { borderTop: "1px solid #273044", padding: "18px 0" }; const muted = { color: "#aeb6c7", lineHeight: 1.6, fontSize: 14 }; const link = { color: "#76f5e3", textDecoration: "none", fontWeight: 800 }; const cards = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 14 }; const card = { border: "1px solid #273044", background: "#101521", padding: 20 }; const how = { maxWidth: 1180, margin: "48px auto", borderTop: "1px solid #273044", paddingTop: 34 }; const editorial = { maxWidth: 1180, margin: "0 auto 38px", borderLeft: "3px solid #76f5e3", background: "#101521", padding: "24px 26px" }; const quick = { maxWidth: 1180, margin: "0 auto 38px", display: "flex", gap: 12, flexWrap: "wrap" as const };
