"use client";

import { FormEvent, useState } from "react";

export default function SubmissionForm() {
  const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false); const [imageInfo, setImageInfo] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setStatus(""); const response = await fetch("/api/game-submissions", { method: "POST", body: new FormData(event.currentTarget) }); const result = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setStatus(result.error || "We could not receive the submission. Please try again."); return; } event.currentTarget.reset(); setImageInfo(""); setStatus("Received. Your submission is private and will be checked against official sources before any editorial decision."); }
  function inspectImage(file?: File) { if (!file) { setImageInfo(""); return; } const url = URL.createObjectURL(file); const image = new Image(); image.onload = () => { const form = document.querySelector<HTMLFormElement>("#game-submission-form"); form?.querySelector<HTMLInputElement>("[name=imageWidth]")!.setAttribute("value", String(image.naturalWidth)); form?.querySelector<HTMLInputElement>("[name=imageHeight]")!.setAttribute("value", String(image.naturalHeight)); setImageInfo(`${image.naturalWidth}×${image.naturalHeight} selected`); URL.revokeObjectURL(url); }; image.onerror = () => { setImageInfo("The selected file could not be read as an image."); URL.revokeObjectURL(url); }; image.src = url; }
  return <form id="game-submission-form" className="submission-form" onSubmit={submit} encType="multipart/form-data">
    <input className="submission-honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" />
    <label>Game title<input name="gameName" maxLength={120} required /></label><label>Studio or creator <span>(optional)</span><input name="studioName" maxLength={120} /></label>
    <label>Official game website<input name="officialUrl" type="url" placeholder="https://yourgame.example" required /></label><label>Official announcement or store page <span>(optional, strongly recommended)</span><input name="sourceUrl" type="url" placeholder="https://…" /></label>
    <label>Coverage lane<select name="coverageLane" defaultValue=""><option value="" disabled>Choose a category</option><option value="mmorpg">MMORPG</option><option value="live_service">Live-service game</option><option value="online_multiplayer">Online multiplayer</option><option value="single_player">Single-player</option><option value="strategy">Strategy</option><option value="shooter">Shooter</option><option value="survival">Survival</option><option value="action_rpg">Action RPG</option><option value="sports_racing">Sports or racing</option><option value="indie_casual">Indie or casual</option><option value="other_digital">Other digital game</option></select></label>
    <label>Lifecycle <span>(optional)</span><select name="lifecycleStatus" defaultValue=""><option value="">Not specified</option><option value="released">Released / live</option><option value="early_access">Early access</option><option value="upcoming">Upcoming</option><option value="active_development">Active development</option><option value="other">Other</option></select></label>
    <label className="submission-full">Platforms <span>(optional)</span><input name="platforms" maxLength={220} placeholder="PC, PlayStation 5, Xbox Series X|S, Switch…" /></label>
    <label className="submission-full">Factual game description<input name="description" minLength={60} maxLength={1200} placeholder="Tell us what the game is and what is confirmed. Please avoid marketing copy and unverified claims." required /></label>
    <label className="submission-full">Anything the review desk should know? <span>(optional)</span><textarea name="submitterNote" maxLength={700} rows={4} placeholder="For example: your strongest official source, launch timing, or a correction to an existing profile." /></label>
    <fieldset className="submission-media"><legend>Optional creator-provided lead image</legend><p>JPEG, PNG, WebP, or AVIF up to 5 MB. Use a landscape 16:9 file; minimum <strong>960×540</strong>, recommended <strong>1600×900</strong>. Upload only artwork or screenshots you own or are authorized to share. It stays private until Owner approval.</p><label>Image file<input name="image" type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={(event) => inspectImage(event.target.files?.[0])} /></label><input type="hidden" name="imageWidth" /><input type="hidden" name="imageHeight" />{imageInfo && <p className="submission-image-info">{imageInfo}</p>}<label>Descriptive image alt text<input name="imageAltText" maxLength={220} placeholder="Describe what the image shows" /></label><label className="submission-check"><input name="rightsConfirmed" type="checkbox" /> I own this image or have explicit permission to let MyRPG review and potentially use it with the submission.</label></fieldset>
    <fieldset className="submission-media submission-permission"><legend>Optional promotional-image permission</legend><p>Prefer not to upload artwork? You can authorize MyRPG to manually review the official URLs above for suitable promotional visuals, including a homepage reference image.</p><label className="submission-check"><input name="promotionalAssetPermission" type="checkbox" /> I control these official pages or have permission to authorize MyRPG to privately review and capture promotional visuals for this submission.</label><p className="submission-permission-note">This is not an automatic crawl. MyRPG will not capture, store, display, or publish an image without a separate Owner review and approval.</p></fieldset>
    <p className="submission-policy">Submitting a game does not guarantee coverage, a review, a ranking, or publication. MyRPG checks direct official sources and keeps every submission private until an Owner decision. We do not use visitor reviews, ratings, or player-count claims as factual evidence.</p>
    <button className="submission-submit" disabled={busy}>{busy ? "Sending…" : "Submit for review"}</button>{status && <p className="submission-status" role="status">{status}</p>}
  </form>;
}
