import { and, eq } from "drizzle-orm";
import { getDb } from "../../db";
import { games, mediaAssets } from "../../db/schema";
import { PublicPage } from "../components/PublicChrome";

export const dynamic = "force-dynamic";

export default async function Games({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const { status } = await searchParams; let rows: any[] = []; const visuals = new Map<string, any>();
  try { const db = getDb(); rows = await db.select().from(games).where(eq(games.published, true)); const assets = await db.select().from(mediaAssets).where(and(eq(mediaAssets.placement, "directory-card"), eq(mediaAssets.status, "approved"))); for (const asset of assets) if (asset.gameId && !visuals.has(asset.gameId)) visuals.set(asset.gameId, asset); } catch { /* Empty state protects private data. */ }
  const shown = status ? rows.filter((game) => game.status === status) : rows;
  return <PublicPage><nav aria-label="Breadcrumb"><a href="/">Home</a> / Games</nav><p style={eyebrow}>MYRPG / GAME DIRECTORY</p><h1 style={heading}>Find an MMO</h1><nav aria-label="Directory filters" style={filters}><a href="/games">All</a><a href="/games?status=live">Live</a><a href="/games?status=early-access">Early access</a><a href="/games?status=announced">Announced</a><a href="/find-my-mmo">Find My MMO →</a></nav><p style={muted}>Only human-approved factual records appear here.</p>{shown.length ? <section style={grid}>{shown.map((game) => { const visual = visuals.get(game.id); return <article key={game.id} style={card}>{visual ? <img src={visual.assetUrl || visual.sourceUrl || ""} alt={visual.altText} width={visual.width || 480} height={visual.height || 270} loading="lazy" style={art} /> : <div aria-label="MyRPG editorial graphic — not gameplay" style={fallback}>{game.setting || "MMO"} · MyRPG editorial graphic — not gameplay</div>}<small style={{ color: "#76f5e3", fontWeight: 800 }}>{game.status.toUpperCase()}</small><h2><a href={`/games/${game.slug}`} style={link}>{game.name}</a></h2><p style={muted}>{game.platforms} · {game.businessModel}</p><p style={muted}>{game.setting} · {game.combat} · {game.focus}</p><small>Recently fact-checked: {game.factCheckedAt?.slice(0, 10)}</small></article>; })}</section> : <section style={empty}><h2>Directory building carefully</h2><p>Approved game profiles will appear as official sources are reviewed.</p></section>}</PublicPage>;
}

export function generateMetadata({ searchParams }: { searchParams: Promise<{ status?: string }> }) { return searchParams.then((query) => query.status ? { title: "MMO Game Directory | MyRPG.IO", description: "Factual, human-approved MMORPG profiles.", alternates: { canonical: "https://myrpg.io/games" }, robots: { index: false, follow: true } } : { title: "MMO Game Directory | MyRPG.IO", description: "Factual, human-approved MMORPG profiles.", alternates: { canonical: "https://myrpg.io/games" } }); }
const eyebrow = { color: "#76f5e3", fontSize: 11, fontWeight: 800, letterSpacing: 1.5, marginTop: 30 }; const heading = { fontSize: "clamp(2.6rem,7vw,5rem)", letterSpacing: "-.06em", margin: "12px 0" }; const muted = { color: "#aeb6c7", lineHeight: 1.6 }; const filters = { display: "flex", gap: 12, flexWrap: "wrap" as const, margin: "22px 0" }; const grid = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(230px,1fr))", gap: 14, marginTop: 28 }; const card = { border: "1px solid #273044", background: "#101521", padding: 20 }; const art = { display: "block", width: "calc(100% + 40px)", height: "auto", aspectRatio: "16 / 9", objectFit: "cover" as const, margin: "-20px -20px 18px" }; const fallback = { minHeight: 110, display: "flex", alignItems: "end", padding: 14, margin: "-20px -20px 18px", background: "linear-gradient(135deg,#151b2c,#112234)", color: "#aeb6c7", fontSize: 11, letterSpacing: .4 }; const link = { color: "#edf3f5", textDecoration: "none" }; const empty = { borderLeft: "3px solid #c9a666", padding: "20px", background: "#101521", marginTop: 28 };
