import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

const stamps = { createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull() };
export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email").notNull().unique(), role: text("role", { enum: ["owner", "admin", "editor"] }).notNull().default("editor"), ...stamps });
export const sources = sqliteTable("sources", { id: text("id").primaryKey(), domain: text("domain").notNull().unique(), label: text("label").notNull(), kind: text("kind").notNull(), approved: integer("approved", { mode: "boolean" }).notNull().default(false), ...stamps });
export const games = sqliteTable("games", { id: text("id").primaryKey(), slug: text("slug").notNull().unique(), name: text("name").notNull(), status: text("status").notNull(), platforms: text("platforms").notNull(), businessModel: text("business_model").notNull(), combat: text("combat").notNull(), setting: text("setting").notNull(), focus: text("focus").notNull(), activity: text("activity"), timeCommitment: text("time_commitment"), releaseDate: text("release_date"), releaseDateConfidence: text("release_date_confidence").notNull().default("unconfirmed"), officialUrl:text("official_url"), sourceUrl:text("source_url"), factCheckedAt:text("fact_checked_at"), directorySummary:text("directory_summary"), sourceConfidence:text("source_confidence").notNull().default("pending"), reviewStatus:text("review_status").notNull().default("draft"), published:integer("published",{mode:"boolean"}).notNull().default(false), ...stamps });
export const calendarItems = sqliteTable("calendar_items", { id: text("id").primaryKey(), gameId:text("game_id").notNull(), title:text("title").notNull(), dateLabel:text("date_label").notNull(), dateConfidence:text("date_confidence").notNull().default("unconfirmed"), sourceUrl:text("source_url").notNull(), factCheckedAt:text("fact_checked_at").notNull(), reviewStatus:text("review_status").notNull().default("draft"), published:integer("published",{mode:"boolean"}).notNull().default(false), ...stamps });
export const articles = sqliteTable("articles", { id: text("id").primaryKey(), slug: text("slug").notNull().unique(), title: text("title").notNull(), summary: text("summary").notNull(), status: text("status", { enum: ["draft", "review", "published", "rejected", "archived"] }).notNull().default("draft"), sourceUrl: text("source_url").notNull(), contentFingerprint: text("content_fingerprint"), confidence: integer("confidence").notNull(), factCheckedAt: text("fact_checked_at"), publishedAt: text("published_at"), ...stamps });
export const agentRuns = sqliteTable("agent_runs", { id: text("id").primaryKey(), agent: text("agent", { enum: ["orchestrator", "scout", "research", "validator", "editor", "director_review"] }).notNull(), status: text("status").notNull(), itemId: text("item_id"), plannedCostCents: integer("planned_cost_cents").notNull().default(0), actualCostCents: integer("actual_cost_cents").notNull().default(0), outputJson: text("output_json"), stoppedReason: text("stopped_reason"), ...stamps });
export const reviewDecisions = sqliteTable("review_decisions", { id: text("id").primaryKey(), articleId: text("article_id").notNull(), decision: text("decision").notNull(), decidedBy: text("decided_by").notNull(), note: text("note"), createdAt: text("created_at").notNull() });
export const approvedMemory = sqliteTable("approved_memory", { id: text("id").primaryKey(), category: text("category").notNull(), body: text("body").notNull(), pinned: integer("pinned", { mode: "boolean" }).notNull().default(true), ...stamps });
export const budgetPolicies = sqliteTable("budget_policies", { id: text("id").primaryKey(), dailyLimitCents: integer("daily_limit_cents").notNull().default(800), perJobLimitCents: integer("per_job_limit_cents").notNull().default(125), liveAgentsEnabled: integer("live_agents_enabled", { mode: "boolean" }).notNull().default(false), emergencyStop: integer("emergency_stop", { mode: "boolean" }).notNull().default(false), ...stamps });
export const auditEvents = sqliteTable("audit_events", { id: text("id").primaryKey(), actorEmail: text("actor_email").notNull(), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id"), details: text("details"), createdAt: text("created_at").notNull() });
export const siteSettings = sqliteTable("site_settings", { id: text("id").primaryKey(), simulationMode: integer("simulation_mode", { mode: "boolean" }).notNull().default(true), networkPromotionsEnabled: integer("network_promotions_enabled", { mode: "boolean" }).notNull().default(true), ...stamps });
export const promotionClicks = sqliteTable("promotion_clicks", { id: text("id").primaryKey(), placement: text("placement").notNull(), createdAt: text("created_at").notNull() });
export const sourceCache = sqliteTable("source_cache", { id: text("id").primaryKey(), normalizedUrl: text("normalized_url").notNull().unique(), contentHash: text("content_hash").notNull(), sourceId: text("source_id").notNull(), lastCheckedAt: text("last_checked_at").notNull(), ...stamps });
export const disagreements = sqliteTable("disagreements", { id: text("id").primaryKey(), articleId: text("article_id"), field: text("field").notNull(), firstValue: text("first_value").notNull(), secondValue: text("second_value").notNull(), status: text("status").notNull().default("open"), ...stamps });
export const mediaAssets = sqliteTable("media_assets", { id: text("id").primaryKey(), articleId: text("article_id"), gameId: text("game_id"), assetUrl: text("asset_url"), r2Key: text("r2_key"), sourceUrl: text("source_url"), sourceType: text("source_type").notNull(), credit: text("credit"), altText: text("alt_text").notNull(), caption: text("caption"), width: integer("width"), height: integer("height"), contentHash: text("content_hash"), placement: text("placement").notNull().default("lead"), status: text("status").notNull().default("pending_review"), ...stamps });
