import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

const stamps = { createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull() };
export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email").notNull().unique(), role: text("role", { enum: ["owner", "admin", "editor"] }).notNull().default("editor"), ...stamps });
export const sources = sqliteTable("sources", { id: text("id").primaryKey(), domain: text("domain").notNull().unique(), label: text("label").notNull(), kind: text("kind").notNull(), approved: integer("approved", { mode: "boolean" }).notNull().default(false), ...stamps });
export const games = sqliteTable("games", { id: text("id").primaryKey(), slug: text("slug").notNull().unique(), name: text("name").notNull(), status: text("status").notNull(), platforms: text("platforms").notNull(), businessModel: text("business_model").notNull(), combat: text("combat").notNull(), setting: text("setting").notNull(), focus: text("focus").notNull(), releaseDate: text("release_date"), ...stamps });
export const articles = sqliteTable("articles", { id: text("id").primaryKey(), slug: text("slug").notNull().unique(), title: text("title").notNull(), summary: text("summary").notNull(), status: text("status", { enum: ["draft", "review", "published", "rejected", "archived"] }).notNull().default("draft"), sourceUrl: text("source_url").notNull(), confidence: integer("confidence").notNull(), factCheckedAt: text("fact_checked_at"), publishedAt: text("published_at"), ...stamps });
export const agentRuns = sqliteTable("agent_runs", { id: text("id").primaryKey(), agent: text("agent", { enum: ["orchestrator", "scout", "research", "validator", "editor", "director_review"] }).notNull(), status: text("status").notNull(), itemId: text("item_id"), plannedCostCents: integer("planned_cost_cents").notNull().default(0), actualCostCents: integer("actual_cost_cents").notNull().default(0), outputJson: text("output_json"), stoppedReason: text("stopped_reason"), ...stamps });
export const reviewDecisions = sqliteTable("review_decisions", { id: text("id").primaryKey(), articleId: text("article_id").notNull(), decision: text("decision").notNull(), decidedBy: text("decided_by").notNull(), note: text("note"), createdAt: text("created_at").notNull() });
export const approvedMemory = sqliteTable("approved_memory", { id: text("id").primaryKey(), category: text("category").notNull(), body: text("body").notNull(), pinned: integer("pinned", { mode: "boolean" }).notNull().default(true), ...stamps });
export const budgetPolicies = sqliteTable("budget_policies", { id: text("id").primaryKey(), dailyLimitCents: integer("daily_limit_cents").notNull().default(800), perJobLimitCents: integer("per_job_limit_cents").notNull().default(125), liveAgentsEnabled: integer("live_agents_enabled", { mode: "boolean" }).notNull().default(false), emergencyStop: integer("emergency_stop", { mode: "boolean" }).notNull().default(false), ...stamps });
